name: Ejecutar scraper imoova diariamente

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # Necesario para hacer push

      - name: Instalar Chromium y dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python3 scraper.py

      - name: Guardar cambios en offers.json
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action Bot"
          git add offers.json
          git commit -m "Update offers.json" || echo "No changes to commit"
          git push
